### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by stephanus-tantiono** [uselocale/locale-laravel#14]
I got 
```cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://app.uselocale.com/api/v2/setup``` when do php artisan locale:setup

**Comment by dtorras** [comment]
Are you trying to run this command under some VPN or firewall? It could also be from an old server.

The API and the web app (https://app.uselocale.com) use the same certificate.

You can find some information on how to deal with the expired certificate problem on this site: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-certificate/

**Comment by stephanus-tantiono** [comment]
I'm mot using any VPN or firewall

**Comment by dtorras** [comment]
Have you reviewed the linked information about root certificates for older systems like Debian 8 or Ubuntu 16.04?  https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-certificate/

From our side, we've reviewed the certificate and all appears to be fine https://www.ssllabs.com/ssltest/analyze.html?d=app.uselocale.com
